version: '3.4'

services:
  e_agenda_medica:
    image: ${DOCKER_REGISTRY-}egenda2024/img
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=agenda#2024
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"

 