version: '3.4'

services:
  e_agenda_medica:
    image: ${DOCKER_REGISTRY-}egenda2024/img
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata

  sqldata:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=agenda#2024
      - POSTGRES_DB=eagenda
    ports:
      - "5432:5432"
